project_name: "netprivate"

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    id: "is-private"
    main: ./cmd/is-private/main.go
    binary: "is-private"
    ldflags:
      - "-extldflags '-static'"
      - "-X 'github.com/ilijamt/netprivate.BuildVersion={{ .Version }}'"
      - "-X 'github.com/ilijamt/netprivate.BuildHash={{ .FullCommit }}'"
      - "-X 'github.com/ilijamt/netprivate.BuildDate={{ .Date }}'"
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ilijamt
    name: netprivate

brews:
  - tap:
      owner: ilijamt
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/ilijamt/blacklist-checker
    description: A small library to test if an IP address is in the private or public range for both IPv4 and IPv6.
    test: |
      system "#{bin}/blacklist-checker version"